### PR TITLE
Fix #153 - handle nats connections that are already connected

### LINKED ISSUE #153: providing a nats connection that is already connected is not properly recognized
In the case where an already connected nats connection is provided, stan.js fails to receive a `connect` event from nats, and thus, the protocol is never initialized and the stan connection stalls.

### PR DESCRIPTION
**Pull request by aricart**
stan.js connections initialize the stan protocol on the nats `connect` event. In cases where the connection is provided, and already connected, this event is never emitted, thus the client hangs.

### CODE REVIEW

File: lib/stan.js [hunk 1]
```diff
@@ -271,116 +271,104 @@ Stan.prototype.initState = function () {
...
 
-      this.emit('connect', this)
-    })
+    this.emit('connect', this)
+  })
+}
+
+// @private
+Stan.prototype.setupHandlers = function () {
+  // if they gave us a connection, it could be connected, so the `connect` event may never fire.
```
Comment (kozlovic) [inline lib/stan.js]: I would have done that in createConnection() since we already check if the connection is owned or not.
